# ============================================================
# 16_core12_GO_process_gene_overlap_visualization.R
# GSE303006 / GENCODE M23
#
# Goal:
#   Summarize leading-edge genes from representative GO BP
#   processes and visualize which genes are shared across
#   multiple processes as:
#     1) binary heatmaps (process x gene)
#     2) bipartite process-gene networks
#     3) process-process Jaccard-overlap networks
#
# Input files are generated by:
#   15_core12_GO_BP_reduce_redundancy_leading_edge_v2.R
#
# Default behavior:
#   - choose top 6 representative GO processes for POSITIVE
#   - choose top 6 representative GO processes for NEGATIVE
#   - keep genes appearing in >= 2 selected processes
#   - if too many such genes, keep top 40 by frequency
#
# Outputs:
#   Positive / negative:
#     - selected representative processes
#     - gene frequency tables
#     - process x gene binary matrices
#     - PDF/PNG heatmaps
#     - PDF/PNG bipartite networks
#     - process-process Jaccard matrices and networks
# ============================================================

# ============================================================
# 0. Settings
# ============================================================

POS_REP_FILE <-
    "GSE303006_M23_core12_GO_BP_positive_representative_top10.tsv"

NEG_REP_FILE <-
    "GSE303006_M23_core12_GO_BP_negative_representative_top10.tsv"

POS_LEADING_FILE <-
    "GSE303006_M23_core12_GO_BP_positive_top10_leading_edge_genes.tsv"

NEG_LEADING_FILE <-
    "GSE303006_M23_core12_GO_BP_negative_top10_leading_edge_genes.tsv"

TOP_N_POS <- 6L
TOP_N_NEG <- 6L

MIN_PROCESS_COUNT_PER_GENE <- 2L
MAX_SHARED_GENES <- 40L

OUT_PREFIX <- "GSE303006_M23_core12_GO"


# ============================================================
# 1. Package checks
# ============================================================

needed <- c(
    "data.table",
    "igraph"
)

missing <- needed[
    !vapply(
        needed,
        requireNamespace,
        quietly = TRUE,
        FUN.VALUE = logical(1)
    )
]

if (length(missing) > 0L) {
    stop(
        paste0(
            "Missing package(s): ",
            paste(missing, collapse = ", "),
            "\n\nInstall with:\n",
            "install.packages(c(",
            paste(
                sprintf("\"%s\"", missing),
                collapse = ", "
            ),
            "))\n"
        )
    )
}

library(data.table)
library(igraph)


# ============================================================
# 2. Input checks
# ============================================================

need_files <- c(
    POS_REP_FILE,
    NEG_REP_FILE,
    POS_LEADING_FILE,
    NEG_LEADING_FILE
)

missing_files <- need_files[
    !file.exists(need_files)
]

if (length(missing_files) > 0L) {
    stop(
        "Missing input file(s):\n",
        paste(missing_files, collapse = "\n")
    )
}


# ============================================================
# 3. Read input tables
# ============================================================

pos_rep <- fread(POS_REP_FILE)
neg_rep <- fread(NEG_REP_FILE)

pos_lead <- fread(POS_LEADING_FILE)
neg_lead <- fread(NEG_LEADING_FILE)

cat("Positive representative terms available :", nrow(pos_rep), "\n")
cat("Negative representative terms available :", nrow(neg_rep), "\n")
cat("Positive leading-edge rows              :", nrow(pos_lead), "\n")
cat("Negative leading-edge rows              :", nrow(neg_lead), "\n")


# ============================================================
# 4. Helper functions
# ============================================================

safe_filename <- function(x) {
    x <- gsub("[^A-Za-z0-9_]+", "_", x)
    x <- gsub("_+", "_", x)
    x <- gsub("^_|_$", "", x)
    x
}

make_short_process_label <- function(dt) {

    paste0(
        dt$representative_rank,
        ". ",
        dt$Description
    )
}

build_binary_matrix <- function(selected_rep, leading_dt) {

    keep_go <- selected_rep$ID

    L <- copy(
        leading_dt[
            GO_ID %in% keep_go
        ]
    )

    rep_info <- selected_rep[
        ,
        .(
            ID,
            representative_rank,
            Description
        )
    ]

    L[
        rep_info,
        on = c("GO_ID" = "ID"),
        `:=`(
            representative_rank = i.representative_rank,
            Description = i.Description
        )
    ]

    # gene frequency across selected processes
    gene_freq <- L[
        ,
        .(
            n_processes = uniqueN(GO_ID),
            processes =
                paste(
                    sort(unique(Description)),
                    collapse = " | "
                ),
            min_rank_score =
                min(core12_gene_rank_score, na.rm = TRUE),
            max_rank_score =
                max(core12_gene_rank_score, na.rm = TRUE),
            mean_rank_score =
                mean(core12_gene_rank_score, na.rm = TRUE)
        ),
        by = gene_name
    ]

    shared <- gene_freq[
        n_processes >=
            MIN_PROCESS_COUNT_PER_GENE
    ][
        order(
            -n_processes,
            -abs(mean_rank_score),
            gene_name
        )
    ]

    if (nrow(shared) > MAX_SHARED_GENES) {
        shared <- shared[
            1:MAX_SHARED_GENES
        ]
    }

    shared_genes <- shared$gene_name

    if (length(shared_genes) == 0L) {

        # fallback: if no genes are shared by >=2 processes,
        # keep top 25 genes by average |rank score|
        fallback <- gene_freq[
            order(
                -abs(mean_rank_score),
                gene_name
            )
        ][
            1:min(25L, .N)
        ]

        shared_genes <- fallback$gene_name
        shared <- fallback
    }

    process_levels <- selected_rep[
        order(representative_rank)
    ]$Description

    Lsub <- unique(
        L[
            gene_name %in% shared_genes,
            .(
                Description,
                representative_rank,
                gene_name
            )
        ]
    )

    Lsub[
        ,
        present := 1L
    ]

    mat_dt <- dcast(
        Lsub,
        Description + representative_rank ~ gene_name,
        value.var = "present",
        fill = 0
    )

    setorder(
        mat_dt,
        representative_rank
    )

    row_labels <- paste0(
        mat_dt$representative_rank,
        ". ",
        mat_dt$Description
    )

    mat <- as.matrix(
        mat_dt[
            ,
            !c("Description", "representative_rank")
        ]
    )

    rownames(mat) <- row_labels

    # reorder columns by frequency, then mean score
    shared <- shared[
        order(
            -n_processes,
            -abs(mean_rank_score),
            gene_name
        )
    ]

    keep_cols <- intersect(
        shared$gene_name,
        colnames(mat)
    )

    mat <- mat[
        ,
        keep_cols,
        drop = FALSE
    ]

    shared <- shared[
        match(
            keep_cols,
            gene_name
        )
    ]

    list(
        matrix = mat,
        gene_frequency = shared,
        leading_subset = L[
            gene_name %in% keep_cols
        ],
        selected_rep = selected_rep
    )
}

plot_binary_heatmap <- function(mat, main, pdf_file, png_file) {

    if (ncol(mat) == 0L || nrow(mat) == 0L) {
        warning("Empty matrix: heatmap skipped for ", main)
        return(invisible(NULL))
    }

    # reorder genes by binary pattern
    if (ncol(mat) >= 2L) {
        oo <- order(
            apply(
                mat,
                2,
                function(x) paste(x, collapse = "")
            ),
            decreasing = TRUE
        )
        mat <- mat[
            ,
            oo,
            drop = FALSE
        ]
    }

    pdf(
        pdf_file,
        width = max(8, 0.22 * ncol(mat) + 3),
        height = max(5, 0.45 * nrow(mat) + 2)
    )
    op <- par(no.readonly = TRUE)
    par(
        mar = c(
            max(8, 0.35 * nchar(colnames(mat))),
            14,
            4,
            2
        )
    )
    image(
        x = seq_len(ncol(mat)),
        y = seq_len(nrow(mat)),
        z = t(mat[nrow(mat):1, , drop = FALSE]),
        axes = FALSE,
        xlab = "",
        ylab = "",
        main = main,
        col = c("white", "black")
    )
    axis(
        1,
        at = seq_len(ncol(mat)),
        labels = colnames(mat),
        las = 2,
        cex.axis = 0.7
    )
    axis(
        2,
        at = seq_len(nrow(mat)),
        labels = rev(rownames(mat)),
        las = 2,
        cex.axis = 0.8
    )
    box()
    par(op)
    dev.off()

    png(
        png_file,
        width = max(1600, 110 * ncol(mat) + 500),
        height = max(900, 90 * nrow(mat) + 300),
        res = 150
    )
    op <- par(no.readonly = TRUE)
    par(
        mar = c(
            max(8, 0.35 * nchar(colnames(mat))),
            14,
            4,
            2
        )
    )
    image(
        x = seq_len(ncol(mat)),
        y = seq_len(nrow(mat)),
        z = t(mat[nrow(mat):1, , drop = FALSE]),
        axes = FALSE,
        xlab = "",
        ylab = "",
        main = main,
        col = c("white", "black")
    )
    axis(
        1,
        at = seq_len(ncol(mat)),
        labels = colnames(mat),
        las = 2,
        cex.axis = 0.7
    )
    axis(
        2,
        at = seq_len(nrow(mat)),
        labels = rev(rownames(mat)),
        las = 2,
        cex.axis = 0.8
    )
    box()
    par(op)
    dev.off()
}

plot_bipartite_network <- function(mat, gene_freq, main, pdf_file, png_file, side_label) {

    if (ncol(mat) == 0L || nrow(mat) == 0L) {
        warning("Empty matrix: bipartite network skipped for ", main)
        return(invisible(NULL))
    }

    edges <- which(
        mat > 0,
        arr.ind = TRUE
    )

    edge_dt <- data.table(
        process = rownames(mat)[edges[, 1]],
        gene = colnames(mat)[edges[, 2]]
    )

    if (nrow(edge_dt) == 0L) {
        warning("No edges found: network skipped for ", main)
        return(invisible(NULL))
    }

    proc_nodes <- data.table(
        name = rownames(mat),
        type = TRUE,
        label = rownames(mat),
        size = 26,
        color = if (side_label == "positive") "tomato" else "steelblue"
    )

    gene_nodes <- data.table(
        name = colnames(mat),
        type = FALSE,
        label = colnames(mat),
        size = 8 + 4 * gene_freq$n_processes[
            match(colnames(mat), gene_freq$gene_name)
        ],
        color = "grey70"
    )

    nodes <- rbind(
        proc_nodes,
        gene_nodes,
        fill = TRUE
    )

    g <- graph_from_data_frame(
        d = edge_dt,
        vertices = nodes,
        directed = FALSE
    )

    V(g)$type <- nodes$type[
        match(V(g)$name, nodes$name)
    ]
    V(g)$color <- nodes$color[
        match(V(g)$name, nodes$name)
    ]
    V(g)$size <- nodes$size[
        match(V(g)$name, nodes$name)
    ]
    V(g)$label <- nodes$label[
        match(V(g)$name, nodes$name)
    ]

    lay <- layout_as_bipartite(
        g,
        types = V(g)$type
    )

    lay[V(g)$type == FALSE, 2] <- lay[V(g)$type == FALSE, 2] - 0.2
    lay[V(g)$type == TRUE,  2] <- lay[V(g)$type == TRUE,  2] + 0.2

    pdf(
        pdf_file,
        width = 12,
        height = 8
    )
    plot(
        g,
        layout = lay,
        vertex.label.cex = ifelse(V(g)$type, 0.75, 0.65),
        vertex.label.dist = 0.2,
        vertex.frame.color = NA,
        edge.color = "grey75",
        edge.width = 1.2,
        main = main,
        margin = 0.15
    )
    dev.off()

    png(
        png_file,
        width = 1800,
        height = 1200,
        res = 150
    )
    plot(
        g,
        layout = lay,
        vertex.label.cex = ifelse(V(g)$type, 0.75, 0.65),
        vertex.label.dist = 0.2,
        vertex.frame.color = NA,
        edge.color = "grey75",
        edge.width = 1.2,
        main = main,
        margin = 0.15
    )
    dev.off()

    invisible(
        list(
            graph = g,
            edges = edge_dt,
            nodes = nodes
        )
    )
}

build_jaccard_matrix <- function(mat) {

    if (nrow(mat) <= 1L) {
        J <- matrix(
            1,
            nrow = nrow(mat),
            ncol = nrow(mat)
        )
        rownames(J) <- rownames(mat)
        colnames(J) <- rownames(mat)
        return(J)
    }

    J <- matrix(
        0,
        nrow = nrow(mat),
        ncol = nrow(mat)
    )

    rownames(J) <- rownames(mat)
    colnames(J) <- rownames(mat)

    for (i in seq_len(nrow(mat))) {
        for (j in seq_len(nrow(mat))) {

            a <- mat[i, ] > 0
            b <- mat[j, ] > 0

            inter <- sum(a & b)
            uni <- sum(a | b)

            J[i, j] <- if (uni > 0) inter / uni else 0
        }
    }

    J
}

plot_process_overlap_network <- function(J, main, pdf_file, png_file, side_label,
                                         threshold = 0.10) {

    diag(J) <- 0

    edge_idx <- which(
        J >= threshold,
        arr.ind = TRUE
    )

    edge_idx <- edge_idx[
        edge_idx[, 1] < edge_idx[, 2],
        ,
        drop = FALSE
    ]

    if (nrow(edge_idx) == 0L) {
        warning("No process-overlap edges above threshold for ", main)
        return(invisible(NULL))
    }

    edge_dt <- data.table(
        from = rownames(J)[edge_idx[, 1]],
        to   = colnames(J)[edge_idx[, 2]],
        weight = J[edge_idx]
    )

    node_dt <- data.table(
        name = rownames(J),
        color = if (side_label == "positive") "tomato" else "steelblue"
    )

    g <- graph_from_data_frame(
        d = edge_dt,
        vertices = node_dt,
        directed = FALSE
    )

    E(g)$width <- 2 + 8 * E(g)$weight
    E(g)$label <- sprintf("%.2f", E(g)$weight)
    E(g)$color <- "grey65"
    V(g)$size <- 28
    V(g)$label.cex <- 0.8
    V(g)$frame.color <- NA
    V(g)$color <- node_dt$color[match(V(g)$name, node_dt$name)]

    lay <- layout_with_fr(g)

    pdf(
        pdf_file,
        width = 10,
        height = 8
    )
    plot(
        g,
        layout = lay,
        main = main,
        margin = 0.15,
        edge.label.cex = 0.8
    )
    dev.off()

    png(
        png_file,
        width = 1600,
        height = 1200,
        res = 150
    )
    plot(
        g,
        layout = lay,
        main = main,
        margin = 0.15,
        edge.label.cex = 0.8
    )
    dev.off()

    invisible(
        list(
            graph = g,
            edges = edge_dt,
            nodes = node_dt
        )
    )
}

run_one_side <- function(rep_dt, lead_dt, top_n, side_label, prefix) {

    selected_rep <- copy(
        rep_dt[
            order(representative_rank)
        ][
            1:min(top_n, .N)
        ]
    )

    cat(
        "\nSelected ",
        side_label,
        " representative processes:\n",
        sep = ""
    )

    print(
        selected_rep[
            ,
            .(
                representative_rank,
                ID,
                Description,
                NES,
                p.adjust
            )
        ]
    )

    built <- build_binary_matrix(
        selected_rep,
        lead_dt
    )

    mat <- built$matrix
    gene_freq <- built$gene_frequency

    # save selected representatives
    fwrite(
        selected_rep,
        paste0(prefix, "_selected_processes.tsv"),
        sep = "\t"
    )

    fwrite(
        gene_freq,
        paste0(prefix, "_shared_gene_frequency.tsv"),
        sep = "\t"
    )

    fwrite(
        as.data.table(
            cbind(
                process = rownames(mat),
                as.data.frame(mat)
            )
        ),
        paste0(prefix, "_process_gene_binary_matrix.tsv"),
        sep = "\t"
    )

    fwrite(
        built$leading_subset[
            order(
                representative_rank,
                leading_edge_rank,
                gene_name
            )
        ],
        paste0(prefix, "_shared_gene_leading_edge_long.tsv"),
        sep = "\t"
    )

    # heatmap
    plot_binary_heatmap(
        mat = mat,
        main = paste0(
            "Core #12 ",
            side_label,
            ": shared leading-edge genes across representative GO processes"
        ),
        pdf_file = paste0(prefix, "_heatmap.pdf"),
        png_file = paste0(prefix, "_heatmap.png")
    )

    # bipartite network
    bip <- plot_bipartite_network(
        mat = mat,
        gene_freq = gene_freq,
        main = paste0(
            "Core #12 ",
            side_label,
            ": process-gene bipartite network"
        ),
        pdf_file = paste0(prefix, "_bipartite_network.pdf"),
        png_file = paste0(prefix, "_bipartite_network.png"),
        side_label = side_label
    )

    if (!is.null(bip)) {

        fwrite(
            bip$edges,
            paste0(prefix, "_bipartite_edges.tsv"),
            sep = "\t"
        )

        fwrite(
            bip$nodes,
            paste0(prefix, "_bipartite_nodes.tsv"),
            sep = "\t"
        )
    }

    # process-process Jaccard
    J <- build_jaccard_matrix(mat)

    fwrite(
        as.data.table(
            cbind(
                process = rownames(J),
                as.data.frame(J)
            )
        ),
        paste0(prefix, "_process_jaccard_matrix.tsv"),
        sep = "\t"
    )

    pnet <- plot_process_overlap_network(
        J = J,
        main = paste0(
            "Core #12 ",
            side_label,
            ": process overlap network (Jaccard)"
        ),
        pdf_file = paste0(prefix, "_process_overlap_network.pdf"),
        png_file = paste0(prefix, "_process_overlap_network.png"),
        side_label = side_label,
        threshold = 0.10
    )

    if (!is.null(pnet)) {
        fwrite(
            pnet$edges,
            paste0(prefix, "_process_overlap_edges.tsv"),
            sep = "\t"
        )
    }

    list(
        selected_rep = selected_rep,
        gene_freq = gene_freq,
        matrix = mat,
        leading_subset = built$leading_subset,
        jaccard = J
    )
}


# ============================================================
# 5. Run positive / negative
# ============================================================

pos_res <- run_one_side(
    rep_dt = pos_rep,
    lead_dt = pos_lead,
    top_n = TOP_N_POS,
    side_label = "positive",
    prefix = paste0(OUT_PREFIX, "_positive")
)

neg_res <- run_one_side(
    rep_dt = neg_rep,
    lead_dt = neg_lead,
    top_n = TOP_N_NEG,
    side_label = "negative",
    prefix = paste0(OUT_PREFIX, "_negative")
)


# ============================================================
# 6. Save combined R object
# ============================================================

bundle <- list(
    parameters = list(
        TOP_N_POS = TOP_N_POS,
        TOP_N_NEG = TOP_N_NEG,
        MIN_PROCESS_COUNT_PER_GENE = MIN_PROCESS_COUNT_PER_GENE,
        MAX_SHARED_GENES = MAX_SHARED_GENES
    ),
    positive = pos_res,
    negative = neg_res
)

saveRDS(
    bundle,
    paste0(OUT_PREFIX, "_process_gene_overlap_visualization.rds")
)


# ============================================================
# 7. Console summary
# ============================================================

cat("\n============================================================\n")
cat("Shared leading-edge gene visualization completed\n")
cat("============================================================\n")

cat("\nPositive side:\n")
cat("  selected processes :", nrow(pos_res$selected_rep), "\n")
cat("  genes in matrix    :", ncol(pos_res$matrix), "\n")
cat("  processes in matrix:", nrow(pos_res$matrix), "\n")

cat("\nNegative side:\n")
cat("  selected processes :", nrow(neg_res$selected_rep), "\n")
cat("  genes in matrix    :", ncol(neg_res$matrix), "\n")
cat("  processes in matrix:", nrow(neg_res$matrix), "\n")

cat("\nTop shared genes (positive):\n")
print(
    pos_res$gene_freq[
        1:min(20L, .N)
    ]
)

cat("\nTop shared genes (negative):\n")
print(
    neg_res$gene_freq[
        1:min(20L, .N)
    ]
)

cat(
    "\nSaved files include:\n",
    paste0(OUT_PREFIX, "_positive_selected_processes.tsv\n"),
    paste0(OUT_PREFIX, "_positive_shared_gene_frequency.tsv\n"),
    paste0(OUT_PREFIX, "_positive_process_gene_binary_matrix.tsv\n"),
    paste0(OUT_PREFIX, "_positive_heatmap.pdf / .png\n"),
    paste0(OUT_PREFIX, "_positive_bipartite_network.pdf / .png\n"),
    paste0(OUT_PREFIX, "_positive_process_overlap_network.pdf / .png\n"),
    paste0(OUT_PREFIX, "_negative_selected_processes.tsv\n"),
    paste0(OUT_PREFIX, "_negative_shared_gene_frequency.tsv\n"),
    paste0(OUT_PREFIX, "_negative_process_gene_binary_matrix.tsv\n"),
    paste0(OUT_PREFIX, "_negative_heatmap.pdf / .png\n"),
    paste0(OUT_PREFIX, "_negative_bipartite_network.pdf / .png\n"),
    paste0(OUT_PREFIX, "_negative_process_overlap_network.pdf / .png\n"),
    paste0(OUT_PREFIX, "_process_gene_overlap_visualization.rds\n"),
    sep = ""
)
