# ============================================================
# 17_core12_CELL03_original4modality_validation.R
# GSE303006 / GENCODE M23
#
# Directly validate the two core #12 gene modules in the
# ORIGINAL/NORMALIZED four modalities across CELL03-positive
# versus CELL03-negative cells.
#
# Modules:
#   Positive module:
#     shared leading-edge genes from the positive GO processes
#
#   Negative module:
#     shared leading-edge genes from the negative GO processes
#
# Cells:
#   top 50 U_CELL[,3]  -> CELL03 positive-loading cells
#   bottom 50 U_CELL[,3] -> CELL03 negative-loading cells
#
# E-P mapping:
#   Positive module genes use core #12 E-P pairs with
#       core_EP_score > 0
#
#   Negative module genes use core #12 E-P pairs with
#       core_EP_score < 0
#
# Original observation units are preserved:
#   RNA       : gene x cell
#   ATAC      : enhancer x cell
#   H3K27ac   : enhancer x cell
#   3D        : 20-kb E-P bin-pair x cell
#
# For ATAC/H3/3D, features are first averaged WITHIN each gene,
# then genes are averaged equally. This avoids reintroducing
# E-P degree bias by allowing high-degree genes to dominate.
#
# Measurements:
#   RNA       : logCP10K
#   ATAC      : logCP10K
#   H3K27ac   : logCP10K
#   3D raw    : Euclidean distance and -log(distance)
#   3D z      : Stage-1 standardized -log(distance), missing -> 0
#
# The script reports:
#   - module score differences between CELL03 +/- cells
#   - replicate-adjusted linear-model group effects
#   - positive-module minus negative-module contrasts
#   - gene-level four-modality effects
#   - heatmaps / boxplot PDFs
# ============================================================


# ============================================================
# 0. Packages
# ============================================================

needed <- c(
    "data.table",
    "Matrix",
    "rhdf5"
)

missing <- needed[
    !vapply(
        needed,
        requireNamespace,
        quietly = TRUE,
        FUN.VALUE = logical(1)
    )
]

if (length(missing) > 0L) {
    stop(
        "Missing package(s): ",
        paste(missing, collapse = ", ")
    )
}

library(data.table)
library(Matrix)
library(rhdf5)


# ============================================================
# 1. Settings
# ============================================================

CELL_COMPONENT <- 3L
TOP_CELL_EACH_SIGN <- 50L

# Modules generated by 16_core12_GO_process_gene_overlap_visualization.R
POS_MODULE_FILE <-
    "GSE303006_M23_core12_GO_positive_shared_gene_frequency.tsv"

NEG_MODULE_FILE <-
    "GSE303006_M23_core12_GO_negative_shared_gene_frequency.tsv"

# All 730,969 core #12 E-P scores generated by script 13
EP_SCORE_FILE <-
    "GSE303006_M23_core12_all730969_EP_scores.rds"

# Stage-2 CELL basis
SMALL_FACTORS_FILE <-
    "GSE303006_M23_stage2_Tucker_small_factors.rds"

# Stage-1 preprocessing / raw-normalized inputs
PREPROCESS_STATS_FILE <-
    "GSE303006_M23_stage1_K20_preprocessing_stats.rds"

ATAC_FILE <-
    "GSE303006_M23_brain_ATAC_enhancer_by_cell_AH3D.rds"

H3_FILE <-
    "GSE303006_M23_brain_H3K27ac_enhancer_by_cell_AH3D.rds"

RNA_FILE <-
    "GSE303006_M23_brain_RNA_logCP10K_gene_by_cell.rds"

H5_3D <-
    "GSE303006_M23_brain_3D_binpair_by_cell.h5"

# Optional metadata generated by script 11.
META_FILE <-
    "GSE303006_M23_final4258_metadata.tsv.gz"

OUT_PREFIX <-
    "GSE303006_M23_core12_CELL03_original4modality"


# ============================================================
# 2. Input checks
# ============================================================

need_files <- c(
    POS_MODULE_FILE,
    NEG_MODULE_FILE,
    EP_SCORE_FILE,
    SMALL_FACTORS_FILE,
    PREPROCESS_STATS_FILE,
    ATAC_FILE,
    H3_FILE,
    RNA_FILE,
    H5_3D
)

missing_files <- need_files[
    !file.exists(need_files)
]

if (length(missing_files) > 0L) {
    stop(
        "Missing input file(s):\n",
        paste(missing_files, collapse = "\n")
    )
}


# ============================================================
# 3. Load module genes
# ============================================================

pos_module_dt <- fread(
    POS_MODULE_FILE
)

neg_module_dt <- fread(
    NEG_MODULE_FILE
)

if (!"gene_name" %in% names(pos_module_dt) ||
    !"gene_name" %in% names(neg_module_dt)) {
    stop(
        "Module gene files must contain gene_name."
    )
}

pos_genes <- unique(
    as.character(
        pos_module_dt$gene_name
    )
)

neg_genes <- unique(
    as.character(
        neg_module_dt$gene_name
    )
)

cat(
    "Positive module genes :",
    length(pos_genes),
    "\n"
)

cat(
    "Negative module genes :",
    length(neg_genes),
    "\n"
)

cat(
    "Genes shared by the two modules :",
    length(
        intersect(
            pos_genes,
            neg_genes
        )
    ),
    "\n"
)


# ============================================================
# 4. Load CELL03 and define top/bottom 50 cells
# ============================================================

F <- readRDS(
    SMALL_FACTORS_FILE
)

if (is.null(F$U_CELL)) {
    stop(
        "U_CELL missing from small_factors."
    )
}

U_CELL <- F$U_CELL

if (CELL_COMPONENT > ncol(U_CELL)) {
    stop(
        "CELL_COMPONENT exceeds number of U_CELL columns."
    )
}

cells_all <- rownames(
    U_CELL
)

if (is.null(cells_all)) {
    stop(
        "U_CELL has no cell row names."
    )
}

cell_loading <- U_CELL[
    ,
    CELL_COMPONENT
]

names(cell_loading) <- cells_all

pos_idx <- order(
    cell_loading,
    decreasing = TRUE
)[
    seq_len(
        min(
            TOP_CELL_EACH_SIGN,
            length(cell_loading)
        )
    )
]

neg_idx <- order(
    cell_loading,
    decreasing = FALSE
)[
    seq_len(
        min(
            TOP_CELL_EACH_SIGN,
            length(cell_loading)
        )
    )
]

pos_cells <- cells_all[
    pos_idx
]

neg_cells <- cells_all[
    neg_idx
]

selected_cells <- c(
    pos_cells,
    neg_cells
)

cell_group <- data.table(
    cell =
        selected_cells,

    CELL03_loading =
        cell_loading[
            selected_cells
        ],

    group =
        factor(
            c(
                rep(
                    "positive",
                    length(pos_cells)
                ),
                rep(
                    "negative",
                    length(neg_cells)
                )
            ),
            levels = c(
                "negative",
                "positive"
            )
        )
)

cell_group[
    ,
    replicate :=
        fifelse(
            grepl("^R1", cell),
            "R1",
            fifelse(
                grepl("^R2", cell),
                "R2",
                fifelse(
                    grepl("^R3", cell),
                    "R3",
                    NA_character_
                )
            )
        )
]

# Optional metadata merge.
if (file.exists(META_FILE)) {

    meta <- fread(
        META_FILE
    )

    if ("cell" %in% names(meta)) {

        meta_small <- meta[
            ,
            setdiff(
                names(meta),
                c(
                    "CELL03_loading",
                    "group",
                    "replicate"
                )
            ),
            with = FALSE
        ]

        cell_group <- merge(
            cell_group,
            meta_small,
            by = "cell",
            all.x = TRUE,
            sort = FALSE
        )

        cell_group <- cell_group[
            match(
                selected_cells,
                cell
            )
        ]
    }
}

fwrite(
    cell_group,
    paste0(
        OUT_PREFIX,
        "_selected_cells.tsv"
    ),
    sep = "\t"
)

cat(
    "\nCELL03 selected-cell replicate counts:\n"
)

print(
    table(
        cell_group$group,
        cell_group$replicate,
        useNA = "ifany"
    )
)


# ============================================================
# 5. Load ALL core #12 E-P scores and select sign-consistent
#    E-P pairs for each gene module
# ============================================================

ep_score <- as.data.table(
    readRDS(
        EP_SCORE_FILE
    )
)

required_ep_cols <- c(
    "stage2_pair_id",
    "enhancer_id",
    "gene_name",
    "binpair_id",
    "core_EP_score"
)

if (!all(required_ep_cols %in% names(ep_score))) {
    stop(
        "EP score object lacks required columns: ",
        paste(
            setdiff(
                required_ep_cols,
                names(ep_score)
            ),
            collapse = ", "
        )
    )
}

ep_score[
    ,
    enhancer_id :=
        as.character(
            enhancer_id
        )
]

ep_score[
    ,
    gene_name :=
        as.character(
            gene_name
        )
]

ep_score[
    ,
    binpair_id :=
        as.integer(
            binpair_id
        )
]

ep_pos <- ep_score[
    gene_name %in% pos_genes &
    core_EP_score > 0
]

ep_neg <- ep_score[
    gene_name %in% neg_genes &
    core_EP_score < 0
]

cat(
    "\nCore-consistent E-P pairs:\n"
)

cat(
    "Positive module E-P :",
    nrow(ep_pos),
    "\n"
)

cat(
    "Negative module E-P :",
    nrow(ep_neg),
    "\n"
)

cat(
    "Positive module genes with >=1 positive E-P :",
    uniqueN(ep_pos$gene_name),
    "/",
    length(pos_genes),
    "\n"
)

cat(
    "Negative module genes with >=1 negative E-P :",
    uniqueN(ep_neg$gene_name),
    "/",
    length(neg_genes),
    "\n"
)

fwrite(
    ep_pos,
    paste0(
        OUT_PREFIX,
        "_positive_module_EP_mapping.tsv.gz"
    ),
    sep = "\t"
)

fwrite(
    ep_neg,
    paste0(
        OUT_PREFIX,
        "_negative_module_EP_mapping.tsv.gz"
    ),
    sep = "\t"
)


# ============================================================
# 6. Build gene -> enhancer / bin-pair lists
#
# Equal-gene weighting:
#   within gene: average linked enhancers/binpairs
#   across gene: average gene-level values
# ============================================================

make_feature_list <- function(
    ep_dt,
    feature_col
) {

    z <- ep_dt[
        ,
        .(
            feature_ids =
                list(
                    unique(
                        get(
                            feature_col
                        )
                    )
                )
        ),
        by = gene_name
    ]

    out <- z$feature_ids
    names(out) <- z$gene_name

    out
}

pos_enh_by_gene <- make_feature_list(
    ep_pos,
    "enhancer_id"
)

neg_enh_by_gene <- make_feature_list(
    ep_neg,
    "enhancer_id"
)

pos_bp_by_gene <- make_feature_list(
    ep_pos,
    "binpair_id"
)

neg_bp_by_gene <- make_feature_list(
    ep_neg,
    "binpair_id"
)

selected_enhancers <- sort(
    unique(
        c(
            unlist(
                pos_enh_by_gene,
                use.names = FALSE
            ),
            unlist(
                neg_enh_by_gene,
                use.names = FALSE
            )
        )
    )
)

selected_binpairs <- sort(
    unique(
        as.integer(
            c(
                unlist(
                    pos_bp_by_gene,
                    use.names = FALSE
                ),
                unlist(
                    neg_bp_by_gene,
                    use.names = FALSE
                )
            )
        )
    )
)

selected_genes <- sort(
    unique(
        c(
            pos_genes,
            neg_genes
        )
    )
)

cat(
    "\nUnique original features used:\n"
)

cat(
    "Genes      :",
    length(selected_genes),
    "\n"
)

cat(
    "Enhancers  :",
    length(selected_enhancers),
    "\n"
)

cat(
    "3D binpairs:",
    length(selected_binpairs),
    "\n"
)


# ============================================================
# 7. Load Stage-1 preprocessing statistics
# ============================================================

st <- readRDS(
    PREPROCESS_STATS_FILE
)

required_stats <- c(
    "cells",
    "enhancers",
    "genes",
    "binpairs",
    "ATAC_depth",
    "H3K27ac_depth",
    "ATAC_mean",
    "ATAC_sd",
    "H3_mean",
    "H3_sd",
    "RNA_mean",
    "RNA_sd",
    "D_mean",
    "D_sd"
)

if (!all(required_stats %in% names(st))) {
    stop(
        "Preprocessing stats missing: ",
        paste(
            setdiff(
                required_stats,
                names(st)
            ),
            collapse = ", "
        )
    )
}

if (!all(selected_cells %in% st$cells)) {
    stop(
        "Some selected cells are absent from preprocessing stats."
    )
}


# ============================================================
# 8. Helper functions
# ============================================================

logCP10K_dense <- function(
    count_matrix,
    depth
) {

    x <- as.matrix(
        count_matrix
    )

    x <- sweep(
        x,
        2,
        as.numeric(depth),
        "/"
    )

    x <- x * 10000

    log1p(
        x
    )
}


z_from_stats <- function(
    x,
    feature_ids,
    all_feature_ids,
    mu,
    sd,
    missing_to_zero = FALSE
) {

    jj <- match(
        feature_ids,
        all_feature_ids
    )

    if (anyNA(jj)) {
        stop(
            "Feature IDs absent from preprocessing statistics."
        )
    }

    zz <- sweep(
        x,
        1,
        mu[jj],
        "-"
    )

    good_sd <-
        is.finite(
            sd[jj]
        ) &
        sd[jj] > 0

    if (any(good_sd)) {
        zz[
            good_sd,
        ] <- sweep(
            zz[
                good_sd,
                ,
                drop = FALSE
            ],
            1,
            sd[jj][good_sd],
            "/"
        )
    }

    if (any(!good_sd)) {
        zz[
            !good_sd,
        ] <- 0
    }

    if (missing_to_zero) {
        zz[
            !is.finite(zz)
        ] <- 0
    }

    zz
}


gene_balanced_matrix <- function(
    feature_matrix,
    feature_by_gene,
    genes,
    feature_ids
) {

    out <- matrix(
        NA_real_,
        nrow = length(genes),
        ncol = ncol(feature_matrix),
        dimnames = list(
            genes,
            colnames(feature_matrix)
        )
    )

    feature_lookup <- seq_along(
        feature_ids
    )

    names(feature_lookup) <- as.character(
        feature_ids
    )

    for (g in genes) {

        ids <- feature_by_gene[[g]]

        if (is.null(ids) ||
            length(ids) == 0L) {
            next
        }

        ii <- unname(
            feature_lookup[
                as.character(ids)
            ]
        )

        ii <- ii[
            !is.na(ii)
        ]

        if (length(ii) == 0L) {
            next
        }

        if (length(ii) == 1L) {

            out[
                g,
            ] <- feature_matrix[
                ii,
            ]

        } else {

            out[
                g,
            ] <- colMeans(
                feature_matrix[
                    ii,
                    ,
                    drop = FALSE
                ],
                na.rm = TRUE
            )
        }
    }

    out[
        is.nan(out)
    ] <- NA_real_

    out
}


module_mean_from_gene_matrix <- function(
    gene_matrix
) {

    y <- colMeans(
        gene_matrix,
        na.rm = TRUE
    )

    y[
        is.nan(y)
    ] <- NA_real_

    y
}


rank_biserial <- function(
    x,
    y
) {

    x <- x[
        is.finite(x)
    ]

    y <- y[
        is.finite(y)
    ]

    n1 <- length(x)
    n2 <- length(y)

    if (n1 == 0L || n2 == 0L) {
        return(
            NA_real_
        )
    }

    rr <- rank(
        c(
            x,
            y
        ),
        ties.method = "average"
    )

    U <- sum(
        rr[
            seq_len(n1)
        ]
    ) -
        n1 *
        (
            n1 + 1
        ) /
        2

    2 *
        U /
        (
            n1 *
            n2
        ) -
        1
}


compare_groups <- function(
    values,
    group,
    replicate
) {

    dt <- data.table(
        value =
            as.numeric(
                values
            ),
        group =
            factor(
                as.character(group),
                levels = c(
                    "negative",
                    "positive"
                )
            ),
        replicate =
            factor(
                replicate
            )
    )

    dt <- dt[
        is.finite(value) &
        !is.na(group)
    ]

    xp <- dt[
        group == "positive",
        value
    ]

    xn <- dt[
        group == "negative",
        value
    ]

    if (length(xp) == 0L ||
        length(xn) == 0L) {

        return(
            data.table(
                n_positive = length(xp),
                n_negative = length(xn),
                mean_positive = NA_real_,
                mean_negative = NA_real_,
                delta_mean_pos_minus_neg = NA_real_,
                median_positive = NA_real_,
                median_negative = NA_real_,
                delta_median_pos_minus_neg = NA_real_,
                rank_biserial = NA_real_,
                wilcox_p = NA_real_,
                lm_group_beta_adjusted_replicate = NA_real_,
                lm_group_p_adjusted_replicate = NA_real_
            )
        )
    }

    wt <- suppressWarnings(
        wilcox.test(
            xp,
            xn,
            exact = FALSE
        )
    )

    lm_beta <- NA_real_
    lm_p <- NA_real_

    dt_lm <- dt[
        !is.na(
            replicate
        )
    ]

    if (
        nrow(dt_lm) >= 10L &&
        uniqueN(
            dt_lm$replicate
        ) >= 2L
    ) {

        fit <- lm(
            value ~ group + replicate,
            data = dt_lm
        )

        cc <- summary(
            fit
        )$coefficients

        rn <- rownames(
            cc
        )

        if ("grouppositive" %in% rn) {
            lm_beta <- cc[
                "grouppositive",
                "Estimate"
            ]

            lm_p <- cc[
                "grouppositive",
                "Pr(>|t|)"
            ]
        }
    }

    data.table(
        n_positive =
            length(xp),

        n_negative =
            length(xn),

        mean_positive =
            mean(xp),

        mean_negative =
            mean(xn),

        delta_mean_pos_minus_neg =
            mean(xp) -
            mean(xn),

        median_positive =
            median(xp),

        median_negative =
            median(xn),

        delta_median_pos_minus_neg =
            median(xp) -
            median(xn),

        rank_biserial =
            rank_biserial(
                xp,
                xn
            ),

        wilcox_p =
            wt$p.value,

        lm_group_beta_adjusted_replicate =
            lm_beta,

        lm_group_p_adjusted_replicate =
            lm_p
    )
}


# ============================================================
# 9. ATAC / H3K27ac:
#    raw counts -> exact Stage-1 logCP10K -> z
# ============================================================

cat(
    "\nLoading ATAC / H3K27ac matrices...\n"
)

ATAC_all <- readRDS(
    ATAC_FILE
)

H3_all <- readRDS(
    H3_FILE
)

if (!all(selected_cells %in% colnames(ATAC_all)) ||
    !all(selected_cells %in% colnames(H3_all))) {
    stop(
        "Selected cells absent from ATAC/H3 matrices."
    )
}

if (!all(selected_enhancers %in% rownames(ATAC_all)) ||
    !all(selected_enhancers %in% rownames(H3_all))) {
    stop(
        "Selected enhancers absent from ATAC/H3 matrices."
    )
}

ATAC_count <- ATAC_all[
    selected_enhancers,
    selected_cells,
    drop = FALSE
]

H3_count <- H3_all[
    selected_enhancers,
    selected_cells,
    drop = FALSE
]

rm(
    ATAC_all,
    H3_all
)

gc()

ATAC_depth <- st$ATAC_depth[
    selected_cells
]

H3_depth <- st$H3K27ac_depth[
    selected_cells
]

if (anyNA(ATAC_depth) ||
    anyNA(H3_depth) ||
    any(ATAC_depth <= 0) ||
    any(H3_depth <= 0)) {
    stop(
        "Invalid ATAC/H3 depth for selected cells."
    )
}

ATAC_log <- logCP10K_dense(
    ATAC_count,
    ATAC_depth
)

H3_log <- logCP10K_dense(
    H3_count,
    H3_depth
)

rownames(ATAC_log) <- selected_enhancers
colnames(ATAC_log) <- selected_cells

rownames(H3_log) <- selected_enhancers
colnames(H3_log) <- selected_cells

ATAC_z <- z_from_stats(
    ATAC_log,
    selected_enhancers,
    st$enhancers,
    st$ATAC_mean,
    st$ATAC_sd,
    missing_to_zero = TRUE
)

H3_z <- z_from_stats(
    H3_log,
    selected_enhancers,
    st$enhancers,
    st$H3_mean,
    st$H3_sd,
    missing_to_zero = TRUE
)

rownames(ATAC_z) <- selected_enhancers
colnames(ATAC_z) <- selected_cells

rownames(H3_z) <- selected_enhancers
colnames(H3_z) <- selected_cells


# ============================================================
# 10. RNA:
#     already stored as logCP10K
# ============================================================

cat(
    "Loading RNA logCP10K matrix...\n"
)

RNA_all <- readRDS(
    RNA_FILE
)

if (!all(selected_cells %in% colnames(RNA_all))) {
    stop(
        "Selected cells absent from RNA matrix."
    )
}

available_genes <- intersect(
    selected_genes,
    rownames(RNA_all)
)

missing_rna_genes <- setdiff(
    selected_genes,
    available_genes
)

if (length(missing_rna_genes) > 0L) {
    warning(
        "RNA matrix missing module genes: ",
        paste(
            missing_rna_genes,
            collapse = ", "
        )
    )
}

RNA_log <- as.matrix(
    RNA_all[
        available_genes,
        selected_cells,
        drop = FALSE
    ]
)

rm(
    RNA_all
)

gc()

RNA_z <- z_from_stats(
    RNA_log,
    available_genes,
    st$genes,
    st$RNA_mean,
    st$RNA_sd,
    missing_to_zero = TRUE
)

rownames(RNA_z) <- available_genes
colnames(RNA_z) <- selected_cells


# ============================================================
# 11. 3D:
#     raw Euclidean distance
#     proximity = -log(distance)
#     Stage-1 z-score of proximity
# ============================================================

cat(
    "Reading selected 3D binpairs x selected cells from HDF5...\n"
)

h5_bp <- as.integer(
    h5read(
        H5_3D,
        "binpair_id"
    )
)

h5_cells <- as.character(
    h5read(
        H5_3D,
        "cell"
    )
)

rows3D <- match(
    selected_binpairs,
    h5_bp
)

cols3D <- match(
    selected_cells,
    h5_cells
)

if (anyNA(rows3D) ||
    anyNA(cols3D)) {
    stop(
        "Selected binpairs/cells absent from 3D HDF5."
    )
}

D_raw <- as.matrix(
    h5read(
        H5_3D,
        "distance",
        index = list(
            rows3D,
            cols3D
        )
    )
)

rownames(D_raw) <- as.character(
    selected_binpairs
)

colnames(D_raw) <- selected_cells

D_raw[
    !is.finite(D_raw) |
    D_raw <= 0
] <- NA_real_

D_prox <- -log(
    D_raw
)

D_z <- z_from_stats(
    D_prox,
    selected_binpairs,
    st$binpairs,
    st$D_mean,
    st$D_sd,
    missing_to_zero = TRUE
)

rownames(D_z) <- as.character(
    selected_binpairs
)

colnames(D_z) <- selected_cells

h5closeAll()


# ============================================================
# 12. Gene-balanced modality matrices for each module
# ============================================================

build_module <- function(
    module_name,
    module_genes,
    enh_by_gene,
    bp_by_gene
) {

    genes_use <- intersect(
        module_genes,
        available_genes
    )

    # RNA: one directly observed row per gene.
    RNA_raw_gene <- RNA_log[
        genes_use,
        ,
        drop = FALSE
    ]

    RNA_z_gene <- RNA_z[
        genes_use,
        ,
        drop = FALSE
    ]

    # ATAC/H3: average linked enhancers WITHIN gene.
    ATAC_raw_gene <- gene_balanced_matrix(
        ATAC_log,
        enh_by_gene,
        genes_use,
        selected_enhancers
    )

    ATAC_z_gene <- gene_balanced_matrix(
        ATAC_z,
        enh_by_gene,
        genes_use,
        selected_enhancers
    )

    H3_raw_gene <- gene_balanced_matrix(
        H3_log,
        enh_by_gene,
        genes_use,
        selected_enhancers
    )

    H3_z_gene <- gene_balanced_matrix(
        H3_z,
        enh_by_gene,
        genes_use,
        selected_enhancers
    )

    # 3D: average linked binpairs WITHIN gene.
    D_raw_gene <- gene_balanced_matrix(
        D_raw,
        bp_by_gene,
        genes_use,
        selected_binpairs
    )

    D_prox_gene <- gene_balanced_matrix(
        D_prox,
        bp_by_gene,
        genes_use,
        selected_binpairs
    )

    D_z_gene <- gene_balanced_matrix(
        D_z,
        bp_by_gene,
        genes_use,
        selected_binpairs
    )

    list(
        module_name =
            module_name,

        genes =
            genes_use,

        RNA_raw_gene =
            RNA_raw_gene,

        RNA_z_gene =
            RNA_z_gene,

        ATAC_raw_gene =
            ATAC_raw_gene,

        ATAC_z_gene =
            ATAC_z_gene,

        H3_raw_gene =
            H3_raw_gene,

        H3_z_gene =
            H3_z_gene,

        D_raw_gene =
            D_raw_gene,

        D_prox_gene =
            D_prox_gene,

        D_z_gene =
            D_z_gene
    )
}

POS <- build_module(
    "positive_module",
    pos_genes,
    pos_enh_by_gene,
    pos_bp_by_gene
)

NEG <- build_module(
    "negative_module",
    neg_genes,
    neg_enh_by_gene,
    neg_bp_by_gene
)


# ============================================================
# 13. Build cell-level module scores
# ============================================================

module_cell_scores <- copy(
    cell_group[
        ,
        .(
            cell,
            CELL03_loading,
            group,
            replicate
        )
    ]
)

add_module_scores <- function(
    dt,
    obj,
    prefix
) {

    dt[
        ,
        paste0(
            prefix,
            "_RNA_logCP10K"
        ) :=
            module_mean_from_gene_matrix(
                obj$RNA_raw_gene
            )
    ]

    dt[
        ,
        paste0(
            prefix,
            "_RNA_z"
        ) :=
            module_mean_from_gene_matrix(
                obj$RNA_z_gene
            )
    ]

    dt[
        ,
        paste0(
            prefix,
            "_ATAC_logCP10K"
        ) :=
            module_mean_from_gene_matrix(
                obj$ATAC_raw_gene
            )
    ]

    dt[
        ,
        paste0(
            prefix,
            "_ATAC_z"
        ) :=
            module_mean_from_gene_matrix(
                obj$ATAC_z_gene
            )
    ]

    dt[
        ,
        paste0(
            prefix,
            "_H3K27ac_logCP10K"
        ) :=
            module_mean_from_gene_matrix(
                obj$H3_raw_gene
            )
    ]

    dt[
        ,
        paste0(
            prefix,
            "_H3K27ac_z"
        ) :=
            module_mean_from_gene_matrix(
                obj$H3_z_gene
            )
    ]

    dt[
        ,
        paste0(
            prefix,
            "_3D_distance"
        ) :=
            module_mean_from_gene_matrix(
                obj$D_raw_gene
            )
    ]

    dt[
        ,
        paste0(
            prefix,
            "_3D_minuslogdistance"
        ) :=
            module_mean_from_gene_matrix(
                obj$D_prox_gene
            )
    ]

    dt[
        ,
        paste0(
            prefix,
            "_3D_z"
        ) :=
            module_mean_from_gene_matrix(
                obj$D_z_gene
            )
    ]

    dt
}

module_cell_scores <- add_module_scores(
    module_cell_scores,
    POS,
    "POS"
)

module_cell_scores <- add_module_scores(
    module_cell_scores,
    NEG,
    "NEG"
)

# Positive minus negative MODULE CONTRAST on standardized values.
module_cell_scores[
    ,
    contrast_RNA_z :=
        POS_RNA_z -
        NEG_RNA_z
]

module_cell_scores[
    ,
    contrast_ATAC_z :=
        POS_ATAC_z -
        NEG_ATAC_z
]

module_cell_scores[
    ,
    contrast_H3K27ac_z :=
        POS_H3K27ac_z -
        NEG_H3K27ac_z
]

module_cell_scores[
    ,
    contrast_3D_z :=
        POS_3D_z -
        NEG_3D_z
]

fwrite(
    module_cell_scores,
    paste0(
        OUT_PREFIX,
        "_cell_module_scores.tsv"
    ),
    sep = "\t"
)


# ============================================================
# 14. Group comparisons for the two modules
# ============================================================

score_spec <- data.table(
    module = c(
        rep("positive_module", 5),
        rep("negative_module", 5)
    ),

    modality = rep(
        c(
            "RNA_logCP10K",
            "ATAC_logCP10K",
            "H3K27ac_logCP10K",
            "3D_minuslogdistance",
            "3D_distance"
        ),
        2
    ),

    column = c(
        "POS_RNA_logCP10K",
        "POS_ATAC_logCP10K",
        "POS_H3K27ac_logCP10K",
        "POS_3D_minuslogdistance",
        "POS_3D_distance",

        "NEG_RNA_logCP10K",
        "NEG_ATAC_logCP10K",
        "NEG_H3K27ac_logCP10K",
        "NEG_3D_minuslogdistance",
        "NEG_3D_distance"
    )
)

module_summary_list <- vector(
    "list",
    nrow(score_spec)
)

for (i in seq_len(
    nrow(score_spec)
)) {

    s <- score_spec[i]

    z <- compare_groups(
        module_cell_scores[[s$column]],
        module_cell_scores$group,
        module_cell_scores$replicate
    )

    z[
        ,
        module :=
            s$module
    ]

    z[
        ,
        modality :=
            s$modality
    ]

    z[
        ,
        score_column :=
            s$column
    ]

    module_summary_list[[i]] <- z
}

module_summary <- rbindlist(
    module_summary_list
)

module_summary[
    ,
    wilcox_FDR :=
        p.adjust(
            wilcox_p,
            method = "BH"
        )
]

module_summary[
    ,
    lm_group_FDR_adjusted_replicate :=
        p.adjust(
            lm_group_p_adjusted_replicate,
            method = "BH"
        )
]

setcolorder(
    module_summary,
    c(
        "module",
        "modality",
        "score_column",
        setdiff(
            names(module_summary),
            c(
                "module",
                "modality",
                "score_column"
            )
        )
    )
)

fwrite(
    module_summary,
    paste0(
        OUT_PREFIX,
        "_module_group_comparisons.tsv"
    ),
    sep = "\t"
)


# ============================================================
# 15. Positive-module minus negative-module contrast
#
# This directly tests whether the two core #12 E-P programs
# separate the CELL03 positive/negative cell axis.
# ============================================================

contrast_spec <- data.table(
    modality = c(
        "RNA_z",
        "ATAC_z",
        "H3K27ac_z",
        "3D_z"
    ),

    column = c(
        "contrast_RNA_z",
        "contrast_ATAC_z",
        "contrast_H3K27ac_z",
        "contrast_3D_z"
    )
)

contrast_list <- vector(
    "list",
    nrow(contrast_spec)
)

for (i in seq_len(
    nrow(contrast_spec)
)) {

    s <- contrast_spec[i]

    z <- compare_groups(
        module_cell_scores[[s$column]],
        module_cell_scores$group,
        module_cell_scores$replicate
    )

    z[
        ,
        modality :=
            s$modality
    ]

    z[
        ,
        score_column :=
            s$column
    ]

    contrast_list[[i]] <- z
}

contrast_summary <- rbindlist(
    contrast_list
)

contrast_summary[
    ,
    wilcox_FDR :=
        p.adjust(
            wilcox_p,
            method = "BH"
        )
]

contrast_summary[
    ,
    lm_group_FDR_adjusted_replicate :=
        p.adjust(
            lm_group_p_adjusted_replicate,
            method = "BH"
        )
]

fwrite(
    contrast_summary,
    paste0(
        OUT_PREFIX,
        "_positive_minus_negative_module_contrast.tsv"
    ),
    sep = "\t"
)


# ============================================================
# 16. Gene-level four-modality effects
#
# For each module gene:
#   RNA gene value
#   mean linked-enhancer ATAC
#   mean linked-enhancer H3K27ac
#   mean linked-binpair 3D proximity
#
# All tests use standardized values; raw group means are also
# reported for direct interpretation.
# ============================================================

gene_level_one_module <- function(
    obj,
    module_label
) {

    genes <- obj$genes

    modality_objects <- list(

        RNA = list(
            raw =
                obj$RNA_raw_gene,
            z =
                obj$RNA_z_gene
        ),

        ATAC = list(
            raw =
                obj$ATAC_raw_gene,
            z =
                obj$ATAC_z_gene
        ),

        H3K27ac = list(
            raw =
                obj$H3_raw_gene,
            z =
                obj$H3_z_gene
        ),

        `3D_proximity` = list(
            raw =
                obj$D_prox_gene,
            z =
                obj$D_z_gene
        )
    )

    ans <- list()
    rr <- 1L

    for (m in names(
        modality_objects
    )) {

        raw_mat <- modality_objects[[m]]$raw

        z_mat <- modality_objects[[m]]$z

        for (g in genes) {

            raw_v <- raw_mat[
                g,
            ]

            z_v <- z_mat[
                g,
            ]

            comp <- compare_groups(
                z_v,
                module_cell_scores$group,
                module_cell_scores$replicate
            )

            posmask <-
                module_cell_scores$group ==
                "positive"

            negmask <-
                module_cell_scores$group ==
                "negative"

            comp[
                ,
                module :=
                    module_label
            ]

            comp[
                ,
                gene_name :=
                    g
            ]

            comp[
                ,
                modality :=
                    m
            ]

            comp[
                ,
                raw_mean_positive :=
                    mean(
                        raw_v[
                            posmask
                        ],
                        na.rm = TRUE
                    )
            ]

            comp[
                ,
                raw_mean_negative :=
                    mean(
                        raw_v[
                            negmask
                        ],
                        na.rm = TRUE
                    )
            ]

            comp[
                ,
                raw_delta_pos_minus_neg :=
                    raw_mean_positive -
                    raw_mean_negative
            ]

            ans[[rr]] <- comp

            rr <- rr + 1L
        }
    }

    out <- rbindlist(
        ans,
        fill = TRUE
    )

    out[
        ,
        FDR_within_module_modality :=
            p.adjust(
                wilcox_p,
                method = "BH"
            ),
        by = modality
    ]

    out
}

gene_level_pos <- gene_level_one_module(
    POS,
    "positive_module"
)

gene_level_neg <- gene_level_one_module(
    NEG,
    "negative_module"
)

gene_level <- rbind(
    gene_level_pos,
    gene_level_neg,
    fill = TRUE
)

fwrite(
    gene_level,
    paste0(
        OUT_PREFIX,
        "_gene_level_4modality_effects.tsv.gz"
    ),
    sep = "\t"
)


# ============================================================
# 17. 3D missingness / coverage QC
# ============================================================

coverage_by_module <- function(
    obj,
    module_label
) {

    observed <- is.finite(
        obj$D_raw_gene
    )

    coverage_cell <- colMeans(
        observed,
        na.rm = TRUE
    )

    dt <- data.table(
        module =
            module_label,

        cell =
            colnames(
                obj$D_raw_gene
            ),

        coverage_fraction =
            coverage_cell
    )

    dt[
        module_cell_scores[
            ,
            .(
                cell,
                group,
                replicate
            )
        ],
        on = "cell",
        `:=`(
            group =
                i.group,
            replicate =
                i.replicate
        )
    ]

    dt
}

coverage_dt <- rbind(
    coverage_by_module(
        POS,
        "positive_module"
    ),
    coverage_by_module(
        NEG,
        "negative_module"
    )
)

fwrite(
    coverage_dt,
    paste0(
        OUT_PREFIX,
        "_3D_coverage_by_cell.tsv"
    ),
    sep = "\t"
)


# ============================================================
# 18. Heatmap of standardized module scores
#
# Rows:
#   POS/NEG x RNA/ATAC/H3/3D
#
# Columns:
#   100 cells ordered by CELL03 loading
# ============================================================

heat_cols <- c(
    "POS_RNA_z",
    "POS_ATAC_z",
    "POS_H3K27ac_z",
    "POS_3D_z",
    "NEG_RNA_z",
    "NEG_ATAC_z",
    "NEG_H3K27ac_z",
    "NEG_3D_z"
)

heat_labels <- c(
    "Positive module: RNA",
    "Positive module: ATAC",
    "Positive module: H3K27ac",
    "Positive module: 3D proximity",
    "Negative module: RNA",
    "Negative module: ATAC",
    "Negative module: H3K27ac",
    "Negative module: 3D proximity"
)

ord_cell <- order(
    module_cell_scores$CELL03_loading,
    decreasing = TRUE
)

heat_mat <- t(
    as.matrix(
        module_cell_scores[
            ord_cell,
            ..heat_cols
        ]
    )
)

rownames(
    heat_mat
) <- heat_labels

colnames(
    heat_mat
) <- module_cell_scores$cell[
    ord_cell
]

# clip only for visualization, not analysis
clip_lim <- 2.5

heat_plot <- pmax(
    pmin(
        heat_mat,
        clip_lim
    ),
    -clip_lim
)

heat_colors <- hcl.colors(
    101,
    palette = "Blue-Red 3",
    rev = TRUE
)

pdf(
    paste0(
        OUT_PREFIX,
        "_module_score_heatmap.pdf"
    ),
    width = 14,
    height = 6
)

par(
    mar = c(
        7,
        15,
        4,
        2
    )
)

image(
    x =
        seq_len(
            ncol(
                heat_plot
            )
        ),

    y =
        seq_len(
            nrow(
                heat_plot
            )
        ),

    z =
        t(
            heat_plot[
                nrow(
                    heat_plot
                ):1,
                ,
                drop = FALSE
            ]
        ),

    col =
        heat_colors,

    zlim =
        c(
            -clip_lim,
            clip_lim
        ),

    axes =
        FALSE,

    xlab =
        "Cells ordered by decreasing CELL03 loading",

    ylab =
        "",

    main =
        "Core #12 modules in CELL03 positive/negative cells"
)

axis(
    2,
    at =
        seq_len(
            nrow(
                heat_plot
            )
        ),
    labels =
        rev(
            rownames(
                heat_plot
            )
        ),
    las = 2,
    cex.axis = 0.8
)

# mark boundary between top50 and bottom50
abline(
    v =
        length(pos_cells) +
        0.5,
    lty = 2,
    lwd = 2
)

box()

dev.off()


# ============================================================
# 19. RNA gene heatmap for the actual module genes
# ============================================================

rna_gene_order <- c(
    intersect(
        pos_genes,
        rownames(RNA_z)
    ),
    intersect(
        neg_genes,
        rownames(RNA_z)
    )
)

RNA_heat <- RNA_z[
    rna_gene_order,
    module_cell_scores$cell[
        ord_cell
    ],
    drop = FALSE
]

RNA_heat <- pmax(
    pmin(
        RNA_heat,
        clip_lim
    ),
    -clip_lim
)

pdf(
    paste0(
        OUT_PREFIX,
        "_RNA_gene_heatmap.pdf"
    ),
    width = 14,
    height = max(
        8,
        0.20 *
            nrow(
                RNA_heat
            ) +
            2
    )
)

par(
    mar = c(
        7,
        8,
        4,
        2
    )
)

image(
    x =
        seq_len(
            ncol(
                RNA_heat
            )
        ),

    y =
        seq_len(
            nrow(
                RNA_heat
            )
        ),

    z =
        t(
            RNA_heat[
                nrow(
                    RNA_heat
                ):1,
                ,
                drop = FALSE
            ]
        ),

    col =
        heat_colors,

    zlim =
        c(
            -clip_lim,
            clip_lim
        ),

    axes =
        FALSE,

    xlab =
        "Cells ordered by decreasing CELL03 loading",

    ylab =
        "",

    main =
        "Core #12 positive/negative module genes: RNA z-scores"
)

axis(
    2,
    at =
        seq_len(
            nrow(
                RNA_heat
            )
        ),
    labels =
        rev(
            rownames(
                RNA_heat
            )
        ),
    las = 2,
    cex.axis = 0.55
)

abline(
    v =
        length(pos_cells) +
        0.5,
    lty = 2,
    lwd = 2
)

box()

dev.off()


# ============================================================
# 20. Boxplot PDF of standardized module scores
# ============================================================

boxplot_file <- paste0(
    OUT_PREFIX,
    "_module_scores_boxplots.pdf"
)

pdf(
    boxplot_file,
    width = 8,
    height = 6
)

for (module_prefix in c(
    "POS",
    "NEG"
)) {

    for (modality_suffix in c(
        "RNA_z",
        "ATAC_z",
        "H3K27ac_z",
        "3D_z"
    )) {

        column_name <- paste0(
            module_prefix,
            "_",
            modality_suffix
        )

        yy <- module_cell_scores[[column_name]]

        boxplot(
            yy ~ module_cell_scores$group,
            xlab =
                "CELL03 loading group",
            ylab =
                column_name,
            main =
                column_name,
            outline =
                FALSE
        )

        stripchart(
            yy ~ module_cell_scores$group,
            vertical =
                TRUE,
            method =
                "jitter",
            pch =
                16,
            cex =
                0.6,
            add =
                TRUE
        )
    }
}

dev.off()


# ============================================================
# 21. Console summary
# ============================================================

cat(
    "\n============================================================\n"
)

cat(
    "Original four-modality validation completed\n"
)

cat(
    "============================================================\n"
)

cat(
    "\nModule-level group comparisons:\n"
)

print(
    module_summary[
        ,
        .(
            module,
            modality,
            mean_positive,
            mean_negative,
            delta_mean_pos_minus_neg,
            rank_biserial,
            wilcox_p,
            wilcox_FDR,
            lm_group_beta_adjusted_replicate,
            lm_group_p_adjusted_replicate,
            lm_group_FDR_adjusted_replicate
        )
    ]
)

cat(
    "\nPositive-module minus negative-module standardized contrast:\n"
)

print(
    contrast_summary[
        ,
        .(
            modality,
            mean_positive,
            mean_negative,
            delta_mean_pos_minus_neg,
            rank_biserial,
            wilcox_p,
            wilcox_FDR,
            lm_group_beta_adjusted_replicate,
            lm_group_p_adjusted_replicate,
            lm_group_FDR_adjusted_replicate
        )
    ]
)

cat(
    "\n3D coverage summary:\n"
)

print(
    coverage_dt[
        ,
        .(
            mean_coverage =
                mean(
                    coverage_fraction,
                    na.rm = TRUE
                ),
            median_coverage =
                median(
                    coverage_fraction,
                    na.rm = TRUE
                )
        ),
        by = .(
            module,
            group
        )
    ]
)

cat(
    "\nTop gene-level effects by |rank-biserial|:\n"
)

print(
    gene_level[
        order(
            -abs(
                rank_biserial
            )
        )
    ][
        1:min(
            40L,
            .N
        ),
        .(
            module,
            gene_name,
            modality,
            raw_mean_positive,
            raw_mean_negative,
            raw_delta_pos_minus_neg,
            delta_mean_pos_minus_neg,
            rank_biserial,
            wilcox_p,
            FDR_within_module_modality
        )
    ]
)


# ============================================================
# 22. Save RDS bundle
# ============================================================

result <- list(

    cell_component =
        CELL_COMPONENT,

    top_cells_each_sign =
        TOP_CELL_EACH_SIGN,

    positive_module_genes =
        pos_genes,

    negative_module_genes =
        neg_genes,

    selected_cells =
        cell_group,

    positive_EP_mapping =
        ep_pos,

    negative_EP_mapping =
        ep_neg,

    positive_module =
        POS,

    negative_module =
        NEG,

    module_cell_scores =
        module_cell_scores,

    module_group_comparisons =
        module_summary,

    positive_minus_negative_module_contrast =
        contrast_summary,

    gene_level_4modality_effects =
        gene_level,

    coverage_3D =
        coverage_dt
)

saveRDS(
    result,
    paste0(
        OUT_PREFIX,
        ".rds"
    )
)


# ============================================================
# 23. Final file list
# ============================================================

cat(
    "\nSaved files:\n",
    paste0(OUT_PREFIX, "_selected_cells.tsv\n"),
    paste0(OUT_PREFIX, "_positive_module_EP_mapping.tsv.gz\n"),
    paste0(OUT_PREFIX, "_negative_module_EP_mapping.tsv.gz\n"),
    paste0(OUT_PREFIX, "_cell_module_scores.tsv\n"),
    paste0(OUT_PREFIX, "_module_group_comparisons.tsv\n"),
    paste0(OUT_PREFIX, "_positive_minus_negative_module_contrast.tsv\n"),
    paste0(OUT_PREFIX, "_gene_level_4modality_effects.tsv.gz\n"),
    paste0(OUT_PREFIX, "_3D_coverage_by_cell.tsv\n"),
    paste0(OUT_PREFIX, "_module_score_heatmap.pdf\n"),
    paste0(OUT_PREFIX, "_RNA_gene_heatmap.pdf\n"),
    paste0(OUT_PREFIX, "_module_scores_boxplots.pdf\n"),
    paste0(OUT_PREFIX, ".rds\n"),
    sep = ""
)
